import { Sprout, Target, Users, ShieldCheck, Cpu, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import Card from '../components/Card';

const teamCards = [
  {
    image: '🧑‍🌾',
    tag: 'Farmers',
    tagColor: 'green',
    title: 'For Field Supervisors',
    description:
      'Designed for Uttarakhand agricultural supervisors who need quick, reliable answers without internet research barriers.',
    variant: 'default',
  },
  {
    image: '🔬',
    tag: 'Technology',
    tagColor: 'blue',
    title: 'AI-Powered Intelligence',
    description:
      'Powered by Google Gemini, fine-tuned with domain constraints to stay focused on practical agricultural advice.',
    variant: 'default',
  },
  {
    image: '🏔️',
    tag: 'Region',
    tagColor: 'purple',
    title: 'Uttarakhand Focus',
    description:
      'Context is everything. Our system prompt is tailored specifically for mountain crops, altitude zones, and local conditions.',
    variant: 'highlight',
  },
];

const values = [
  {
    icon: <Target size={20} />,
    title: 'Purpose-Built',
    desc: 'Focused only on agricultural advisory — not a general-purpose chatbot.',
  },
  {
    icon: <ShieldCheck size={20} />,
    title: 'Safety First',
    desc: 'Every response carries a disclaimer to consult extension officers.',
  },
  {
    icon: <Users size={20} />,
    title: 'Farmer-Centric',
    desc: 'Plain language, no jargon — designed for supervisors in the field.',
  },
  {
    icon: <Cpu size={20} />,
    title: 'Gemini API',
    desc: "Google's Gemini free-tier powers fast, reliable, accurate responses.",
  },
];

export default function About() {
  return (
    <div className="min-h-screen pt-24 pb-16 page-enter">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Page header */}
        <div className="text-center mb-16">
          <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-green-500 to-green-700 flex items-center justify-center mx-auto mb-6 glow-green">
            <Sprout size={30} className="text-white" />
          </div>
          <h1 className="text-4xl sm:text-5xl font-extrabold text-white font-['Plus_Jakarta_Sans'] mb-4">
            About <span className="gradient-text">AgriChat</span>
          </h1>
          <p className="text-gray-400 text-lg max-w-2xl mx-auto leading-relaxed">
            AgriChat is an AI-powered agricultural advisory platform built specifically for supervisors
            and farmers in Uttarakhand's mountain regions. Ask questions in plain language and receive
            practical, localised crop guidance.
          </p>
        </div>

        {/* Mission */}
        <div className="glass rounded-2xl p-8 mb-10 border border-green-900/30">
          <h2 className="text-2xl font-bold text-white font-['Plus_Jakarta_Sans'] mb-4">
            Our Mission
          </h2>
          <p className="text-gray-400 leading-relaxed">
            Uttarakhand's mountain agriculture faces unique challenges — steep terrain, erratic rainfall,
            limited access to experts, and diverse microclimates. AgriChat bridges the gap between
            modern AI and traditional farming knowledge, giving every supervisor instant access to
            expert guidance tailored to their specific region, crop, and season.
          </p>
        </div>

        {/* Cards */}
        <div className="grid sm:grid-cols-3 gap-5 mb-14">
          {teamCards.map((card, idx) => (
            <Card key={idx} {...card} />
          ))}
        </div>

        {/* Values */}
        <h2 className="text-2xl font-bold text-white font-['Plus_Jakarta_Sans'] mb-6">
          Core Principles
        </h2>
        <div className="grid sm:grid-cols-2 gap-4 mb-14">
          {values.map((val) => (
            <div
              key={val.title}
              className="flex items-start gap-4 p-5 rounded-xl bg-[#111a11] border border-green-900/20 hover:border-green-700/30 transition-colors"
            >
              <div className="w-10 h-10 rounded-xl bg-green-900/40 border border-green-700/20 flex items-center justify-center text-green-400 flex-shrink-0">
                {val.icon}
              </div>
              <div>
                <div className="font-semibold text-white mb-1">{val.title}</div>
                <div className="text-sm text-gray-500">{val.desc}</div>
              </div>
            </div>
          ))}
        </div>

        {/* Disclaimer box */}
        <div className="p-6 rounded-2xl bg-amber-900/10 border border-amber-800/20 mb-10">
          <h3 className="text-base font-bold text-amber-400 mb-2">⚠️ Important Disclaimer</h3>
          <p className="text-sm text-amber-500/80 leading-relaxed">
            All responses provided by AgriChat are generated by an AI model and are intended for
            informational and advisory purposes only. They do not constitute professional agricultural
            advice. Users are strongly encouraged to verify all recommendations with a{' '}
            <strong className="text-amber-400">licensed agricultural extension officer</strong> before
            making any significant farming decisions, especially those involving pesticides,
            fertilizers, or financial investments.
          </p>
        </div>

        {/* CTA */}
        <div className="text-center">
          <Link to="/chat" className="btn-primary text-base px-8 py-4">
            Start Chatting <ArrowRight size={18} />
          </Link>
        </div>
      </div>
    </div>
  );
}
